/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void roll(){
        ArrayList<Integer> rolledDie = Library.roll(5);
        assertEquals(5, rolledDie.size());
    }
    @Test void duplicates(){
        Set<Boolean> sameNum = Library.duplicates(true);
        assertTrue(true);
    }
}
