/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static ArrayList<Integer> roll(int n){
        ArrayList<Integer> rolledDie = new ArrayList<>();
        Random dieRoll = new Random();
        int face;
        for (int roll = 1; roll <= n; roll++){
            face = 1 + dieRoll.nextInt(6);

            rolledDie.add(face);
        }
        return rolledDie;
    }
    public static Set<Boolean> containsDuplicates(int [] rolledDie){
        Set<Boolean> duplicates = new HashSet<>();

        for(int i = 0; i< rolledDie.length; i++){
            for(int j = 1; j < rolledDie.length; j++){
                if (rolledDie[i] == rolledDie[j] && i!=j){
                    System.out.println("true");
                }
            }
        }
        return duplicates;
    }

}
