/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void constructorTest(){

        Restaurant newPlace = new Restaurant("Firecracker Lounge", 4.5f, 15.95f);
        assertInstanceOf(Restaurant.class, newPlace);
    }

    @Test void testRestMethod(){

//        Restaurant.cuisine("Latin");
        Restaurant.familyFriendly(true);
        Restaurant.bar(true);
        Restaurant.danceFloor(true);


//        assertEquals("Latin", Restaurant.cuisine("Latin"));
        assertTrue(Restaurant.familyFriendly(true));
        assertTrue(Restaurant.bar(true));
        assertTrue(Restaurant.danceFloor(true));
    }

    @Test void toStringTest(){
        Restaurant.toString("Latin");
        assertEquals("Latin", Restaurant.toString("Latin"), "Latin");
    }

    @Test void reviewConstructor(){
        Review msg = new Review("Rob Jones", "Food was great!", 4.5f);
        assertInstanceOf(Review.class, msg);
  }
}
